[package]
name = "godot_demo_rust"
version = "0.1.0"
edition = "2018"
publish = ["rustcc"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
gdnative = "0.9.3"
rand = "0.8.4"